spring.application.name=evenMad
#Info API
server.port=8080
server.servlet.context-path=/api
# MongoDB string connection
spring.mongodb.uri=${MONGODB_URI}
#Transforma nombre atributos a snake_case
spring.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
# limitacion y default de paginacion
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
# ignora mayus minus alrecibir un enumerado
spring.jackson.mapper.accept-case-insensitive-enums=true