#Creacion de indices de modelos automatica
spring.mongodb.auto-index-creation=true

# Logs de debugging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.web=DEBUG
