# Creacion de indices de las colecciones no automatica
spring.mongodb.auto-index-creation=false
# Solo logs de errores
logging.level.org.springframework.data.mongodb.core.MongoTemplate=ERROR
logging.level.org.springframework.web=ERROR
